spring.config.import=optional:file:.env[.properties],optional:file:services/comment-service/.env[.properties]
spring.application.name=comment-service

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${DIALECT:org.hibernate.dialect.MySQLDialect}

# Server Configuration
server.port=${SERVER_PORT:8086}

# JWT Configuration
jwt.secret=${JWT_SECRET}

logging.level.com.flowboard=DEBUG
